// Validation report generator: replays an OpenMC-generated depletion case with
// this engine and writes the full comparison as JSON for
// validation/report/render_report.py to turn into a report.
//
// This is the measurement half only. It states what the engine produced and
// what the reference says, plus structural facts about the input chain that
// explain which nuclides the topology leaves under-determined. It draws no
// conclusions and applies no corrections; the tolerance is a reporting
// threshold, not an assertion (see --fail-over-tolerance to make it one).
//
//   vera_report --data <dir> [--case <name>] [--out <file>] [--tolerance <x>]
//
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "cram/version.hpp"
#include "validation/vera_case.hpp"

using namespace cram;
using namespace cram_validation;
namespace fs = std::filesystem;

namespace {

// --- a very small JSON writer ----------------------------------------------
//
// Hand-rolled rather than pulling in a dependency: the document is written once,
// top to bottom, and every key here is a literal. Only the numeric formatting
// matters, and %.10g keeps the file readable while carrying far more precision
// than a report needs.

class Json {
public:
  explicit Json(std::ostream& os) : os_(os) {}

  void beginObject(const char* key = nullptr) { begin('{', key); }
  void endObject() { end('}'); }
  void beginArray(const char* key = nullptr) { begin('[', key); }
  void endArray() { end(']'); }

  void key(const char* k) {
    comma();
    newline();
    os_ << '"' << k << "\": ";
    pending_ = true;
  }

  void value(const std::string& s) {
    prefix();
    os_ << '"';
    for (char c : s) {
      if (c == '"' || c == '\\')
        os_ << '\\' << c;
      else if (static_cast<unsigned char>(c) < 0x20)
        os_ << ' ';
      else
        os_ << c;
    }
    os_ << '"';
  }
  void value(const char* s) { value(std::string(s)); }
  void value(bool b) {
    prefix();
    os_ << (b ? "true" : "false");
  }
  void value(int i) {
    prefix();
    os_ << i;
  }
  void value(std::size_t i) {
    prefix();
    os_ << i;
  }
  void value(double d) {
    prefix();
    if (!std::isfinite(d)) {
      os_ << "null";  // JSON has no NaN/Inf
      return;
    }
    char buf[40];
    std::snprintf(buf, sizeof buf, "%.10g", d);
    os_ << buf;
  }
  void null() {
    prefix();
    os_ << "null";
  }

  void member(const char* k, const std::string& v) {
    key(k);
    value(v);
  }
  void member(const char* k, const char* v) {
    key(k);
    value(v);
  }
  void member(const char* k, double v) {
    key(k);
    value(v);
  }
  void member(const char* k, int v) {
    key(k);
    value(v);
  }
  void member(const char* k, std::size_t v) {
    key(k);
    value(v);
  }
  void member(const char* k, bool v) {
    key(k);
    value(v);
  }

private:
  void begin(char c, const char* k) {
    if (k != nullptr)
      key(k);
    prefix();
    os_ << c;
    ++depth_;
    first_.push_back(true);
  }
  void end(char c) {
    const bool empty = first_.empty() || first_.back();
    if (!first_.empty())
      first_.pop_back();
    --depth_;
    if (!empty)
      newline();
    os_ << c;
    if (!first_.empty())
      first_.back() = false;
  }
  void comma() {
    if (!first_.empty() && !first_.back())
      os_ << ',';
    if (!first_.empty())
      first_.back() = false;
  }
  void prefix() {
    if (pending_) {  // value follows a key: no comma, no indent
      pending_ = false;
      return;
    }
    comma();
    newline();
  }
  void newline() {
    os_ << '\n';
    for (int i = 0; i < depth_; ++i)
      os_ << "  ";
  }

  std::ostream& os_;
  int depth_ = 0;
  bool pending_ = false;
  std::vector<bool> first_;
};

// SOURCE_DATE_EPOCH, when set, so a report can be regenerated byte-identically.
// std::getenv is deprecated-with-a-warning under MSVC, which CI builds with
// warnings-as-errors, hence the split.
bool sourceDateEpoch(std::time_t& out) {
#ifdef _MSC_VER
  char* buf = nullptr;
  std::size_t len = 0;
  if (_dupenv_s(&buf, &len, "SOURCE_DATE_EPOCH") != 0 || buf == nullptr)
    return false;
  out = static_cast<std::time_t>(std::strtoll(buf, nullptr, 10));
  std::free(buf);
  return true;
#else
  const char* sde = std::getenv("SOURCE_DATE_EPOCH");
  if (sde == nullptr)
    return false;
  out = static_cast<std::time_t>(std::strtoll(sde, nullptr, 10));
  return true;
#endif
}

std::string utcTimestamp() {
  std::time_t now = std::time(nullptr);
  std::time_t sde = 0;
  if (sourceDateEpoch(sde))
    now = sde;
  std::tm tmv{};
#ifdef _WIN32
  gmtime_s(&tmv, &now);
#else
  gmtime_r(&now, &tmv);
#endif
  char buf[32];
  std::strftime(buf, sizeof buf, "%Y-%m-%dT%H:%M:%SZ", &tmv);
  return buf;
}

double percentile(std::vector<double> v, double p) {
  if (v.empty())
    return 0.0;
  std::sort(v.begin(), v.end());
  const double idx = p * static_cast<double>(v.size() - 1);
  const auto lo = static_cast<std::size_t>(std::floor(idx));
  const auto hi = static_cast<std::size_t>(std::ceil(idx));
  return v[lo] + (v[hi] - v[lo]) * (idx - static_cast<double>(lo));
}

struct Options {
  fs::path data = CRAM_VALIDATION_DATA_DIR;
  std::string caseName = "vera_pin1a";
  fs::path out = "vera_report.json";
  double tolerance = 1e-3;
  int failOver = -1;  // >= 0 turns the tolerance into a gate
};

[[noreturn]] void usage(int code) {
  std::fprintf(code == 0 ? stdout : stderr,
               "usage: vera_report [--data DIR] [--case NAME] [--out FILE]\n"
               "                   [--tolerance X] [--fail-over-tolerance N]\n"
               "\n"
               "  --data DIR                directory holding the case directories\n"
               "  --case NAME               case subdirectory (default vera_pin1a)\n"
               "  --out FILE                JSON output path (default vera_report.json)\n"
               "  --tolerance X             reporting threshold on relative error (1e-3)\n"
               "  --fail-over-tolerance N   exit 1 if more than N nuclides exceed it\n");
  std::exit(code);
}

}  // namespace

int main(int argc, char** argv) {
  Options opt;
  for (int i = 1; i < argc; ++i) {
    const auto need = [&](const char* what) {
      if (i + 1 >= argc) {
        std::fprintf(stderr, "vera_report: %s needs a value\n", what);
        usage(2);
      }
      return argv[++i];
    };
    if (std::strcmp(argv[i], "--data") == 0)
      opt.data = need("--data");
    else if (std::strcmp(argv[i], "--case") == 0)
      opt.caseName = need("--case");
    else if (std::strcmp(argv[i], "--out") == 0)
      opt.out = need("--out");
    else if (std::strcmp(argv[i], "--tolerance") == 0)
      opt.tolerance = std::stod(need("--tolerance"));
    else if (std::strcmp(argv[i], "--fail-over-tolerance") == 0)
      opt.failOver = std::stoi(need("--fail-over-tolerance"));
    else if (std::strcmp(argv[i], "--help") == 0 || std::strcmp(argv[i], "-h") == 0)
      usage(0);
    else {
      std::fprintf(stderr, "vera_report: unknown argument '%s'\n", argv[i]);
      usage(2);
    }
  }

  const fs::path root = opt.data / opt.caseName;
  if (!caseExists(root)) {
    std::fprintf(stderr,
                 "vera_report: no reference case at %s\n"
                 "  (generate it offline with validation/openmc/generate_vera_pin.py)\n",
                 root.string().c_str());
    return 3;
  }

  const VeraCase c = loadVeraCase(root);
  const std::vector<Eigen::VectorXd> traj = marchPredictor(c);
  const auto last = static_cast<std::size_t>(c.steps);

  // The comparison set: every nuclide the reference reports as present at end of
  // life. Anything with a zero reference has no relative error to speak of.
  struct Row {
    int index;
    std::string name;
    bool curated;
    double finalErr;
  };
  std::vector<Row> rows;
  for (int j = 0; j < c.refDensity[last].size(); ++j) {
    if (!(c.refDensity[last](j) > 0.0))
      continue;
    const Zai& z = c.chain.nuclides()[static_cast<std::size_t>(j)];
    const std::string name =
        elementSymbol(z.z) + std::to_string(z.a) + (z.i > 0 ? "_m" + std::to_string(z.i) : "");
    bool curated = false;
    for (const char* n : kBenchmarkNuclides)
      curated = curated || (name == n);
    const double e = std::abs(traj[last](j) - c.refDensity[last](j)) / c.refDensity[last](j);
    rows.push_back({j, name, curated, e});
  }
  std::sort(rows.begin(), rows.end(),
            [](const Row& a, const Row& b) { return a.finalErr > b.finalErr; });

  std::vector<double> allErr, curatedErr;
  int over = 0, curatedOver = 0;
  for (const Row& r : rows) {
    allErr.push_back(r.finalErr);
    if (r.finalErr > opt.tolerance)
      ++over;
    if (r.curated) {
      curatedErr.push_back(r.finalErr);
      if (r.finalErr > opt.tolerance)
        ++curatedOver;
    }
  }

  const std::vector<Zai> noYields = fissionWithoutYields(c);
  const std::vector<Zai> sfOnly = decaysOnlyBySpontaneousFission(c);

  std::ofstream os(opt.out);
  if (!os) {
    std::fprintf(stderr, "vera_report: cannot write %s\n", opt.out.string().c_str());
    return 4;
  }
  Json j(os);
  j.beginObject();
  j.member("schema", 1);
  j.member("generated_utc", utcTimestamp());
  j.member("cram_version", CRAM_VERSION_STRING);
  j.member("tolerance", opt.tolerance);

  j.beginObject("case");
  j.member("name", opt.caseName);
  j.member("path", root.generic_string());
  j.endObject();

  j.beginObject("solver");
  j.member("integrator", "predictor");
  j.member("cram_order", 48);
  j.member("normalization", "constant flux, re-set per step from schedule.csv");
  j.member("initial_condition", "reference density at step 0");
  j.endObject();

  j.beginObject("chain");
  j.member("nuclides", static_cast<int>(c.chain.size()));
  j.member("reaction_channels", c.topology.size());
  j.beginObject("diagnostics");
  j.member("unparsed_nuclides", c.diagnostics.unparsedNuclides);
  j.member("unparsed_decay_targets", c.diagnostics.unparsedDecayTargets);
  j.member("unparsed_yield_products", c.diagnostics.unparsedYieldProducts);
  j.member("unmodeled_reactions", c.diagnostics.unmodeledReactions);
  j.member("clean", c.diagnostics.clean());
  j.endObject();
  j.beginArray("fission_without_yield_table");
  for (const Zai& z : noYields)
    j.value(elementSymbol(z.z) + std::to_string(z.a) + (z.i > 0 ? "_m" + std::to_string(z.i) : ""));
  j.endArray();
  j.beginArray("decay_only_spontaneous_fission");
  for (const Zai& z : sfOnly)
    j.value(elementSymbol(z.z) + std::to_string(z.a) + (z.i > 0 ? "_m" + std::to_string(z.i) : ""));
  j.endArray();
  j.endObject();

  j.beginObject("schedule");
  j.member("steps", c.steps);
  j.member("total_seconds", c.totalSeconds());
  j.member("total_days", c.totalSeconds() / 86400.0);
  j.beginArray("dt_seconds");
  for (double d : c.dt)
    j.value(d);
  j.endArray();
  j.beginArray("flux");
  for (double f : c.flux)
    j.value(f);
  j.endArray();
  j.beginArray("cumulative_days");
  {
    double t = 0.0;
    j.value(0.0);
    for (double d : c.dt) {
      t += d;
      j.value(t / 86400.0);
    }
  }
  j.endArray();
  j.endObject();

  j.beginArray("benchmark_nuclides");
  for (const char* n : kBenchmarkNuclides)
    j.value(n);
  j.endArray();

  j.beginArray("nuclides");
  for (const Row& r : rows) {
    j.beginObject();
    j.member("name", r.name);
    j.member("curated", r.curated);
    j.member("final_relerr", r.finalErr);
    j.beginArray("cram");
    for (std::size_t k = 0; k <= last; ++k)
      j.value(traj[k](r.index));
    j.endArray();
    j.beginArray("ref");
    for (std::size_t k = 0; k <= last; ++k)
      j.value(c.refDensity[k](r.index));
    j.endArray();
    j.beginArray("relerr");
    for (std::size_t k = 0; k <= last; ++k) {
      const double ref = c.refDensity[k](r.index);
      if (ref > 0.0)
        j.value(std::abs(traj[k](r.index) - ref) / ref);
      else
        j.null();
    }
    j.endArray();
    j.endObject();
  }
  j.endArray();

  j.beginObject("summary");
  j.member("compared", rows.size());
  j.member("over_tolerance", over);
  j.member("worst", rows.empty() ? 0.0 : rows.front().finalErr);
  j.member("worst_nuclide", rows.empty() ? std::string("-") : rows.front().name);
  j.member("median", percentile(allErr, 0.5));
  j.member("p95", percentile(allErr, 0.95));
  j.beginObject("benchmark_subset");
  j.member("compared", curatedErr.size());
  j.member("over_tolerance", curatedOver);
  j.member("worst",
           curatedErr.empty() ? 0.0 : *std::max_element(curatedErr.begin(), curatedErr.end()));
  j.endObject();
  j.endObject();

  j.endObject();
  os << '\n';
  os.close();

  std::printf("vera_report: %s -> %s\n", opt.caseName.c_str(), opt.out.string().c_str());
  std::printf("  compared %zu nuclides, %d over %.1e (worst %.4e on %s)\n", rows.size(), over,
              opt.tolerance, rows.empty() ? 0.0 : rows.front().finalErr,
              rows.empty() ? "-" : rows.front().name.c_str());
  std::printf("  benchmark subset: %zu compared, %d over tolerance\n", curatedErr.size(),
              curatedOver);
  if (!noYields.empty())
    std::printf("  note: %zu fission channel(s) have no usable yield table in this chain\n",
                noYields.size());
  if (!sfOnly.empty())
    std::printf("  note: %zu nuclide(s) decay only by spontaneous fission\n", sfOnly.size());

  if (opt.failOver >= 0 && over > opt.failOver) {
    std::fprintf(stderr, "vera_report: %d nuclides over tolerance, limit is %d\n", over,
                 opt.failOver);
    return 1;
  }
  return 0;
}
